#!/bin/sh

# PROVIDE: FortuneCoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# FortuneCoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable FortuneCoin service.
# FortuneCoin_config (path): Set to /usr/local/etc/FortuneCoin.conf by default.
# FortuneCoin_user:  The user account FortuneCoin daemon runs as. It uses 'root' user by default.
# FortuneCoin_group: The group account FortuneCoin daemon runs as. It uses 'wheel' group by default.
# FortuneCoin_datadir (str): Default to "/var/db/FortuneCoin". Base data directory.

. /etc/rc.subr

name=FortuneCoin
rcvar=FortuneCoin_enable

: ${FortuneCoin_enable:=NO}
: ${FortuneCoin_config=/usr/local/etc/FortuneCoin.conf}
: ${FortuneCoin_datadir=/var/db/FortuneCoin}
: ${FortuneCoin_user="root"}
: ${FortuneCoin_group="wheel"}

required_files=${FortuneCoin_config}
command=/usr/local/bin/FortuneCoind
FortuneCoin_chdir=${FortuneCoin_datadir}
pidfile="${FortuneCoin_datadir}/FortuneCoind.pid"
stop_cmd=FortuneCoin_stop
command_args="-conf=${FortuneCoin_config} -datadir=${FortuneCoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

FortuneCoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${FortuneCoin_datadir}
	[ $? -eq 0 ] && chown -R ${FortuneCoin_user}:${FortuneCoin_group} ${FortuneCoin_datadir}
}

FortuneCoin_prestart()
{
	if [ ! -d "${FortuneCoin_datadir}/." ]; then
		FortuneCoin_create_datadir || return 1
	fi
}

FortuneCoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

FortuneCoin_stop()
{
    FortuneCoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${FortuneCoin_config} -datadir=${FortuneCoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
